apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
      id: "0"
  template:
    metadata:
      labels:
        app: elasticsearch
        id: "0"
    spec:
      containers:
        - name: elasticsearch
          image: arm64v8/elasticsearch:7.14.2
          ports:
            - containerPort: 9200
