apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  labels:
    name: elasticsearch-service
spec:
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
      name: es-port
  selector:
    app: elasticsearch
  type: ClusterIP