apiVersion: v1
kind: Service
metadata:
  name: es-service
  labels:
    name: es
spec:
  ports:
  - port: 9200
    name: es-port
    protocol: TCP
  selector:
    app: es
    id: "0"
  type: LoadBalancer