apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  labels:
    name: kibana-service
spec:
  ports:
    - port: 5601
      targetPort: 5601
      protocol: TCP
      name: kibana-port
  selector:
    app: kibana
  type: ClusterIP